Vagrant.configure("2") do |config|

  $script = <<-SCRIPT
    apt-get -y update
    apt-get -y install redis
    apt-get -y ruby
    gem install redis
    systemctl stop redis-server
    systemctl disable redis-server
    echo 192.168.59.100 master.local master >> /etc/hosts
    echo 192.168.59.101 slave.local  slave  >> /etc/hosts
    echo 192.168.59.102 client.local client >> /etc/hosts
  SCRIPT

  config.vm.box = "generic/debian12"
  config.vm.synced_folder "src/", "/src"
  config.ssh.insert_key = false # use ~/.vagrant.d/insecure_private_key

  config.vm.provision "shell",
    inline: $script

  nodes = [
    "master",
    "slave",
    "client",
  ]

  nodes.each_with_index do |n,i|
    config.vm.define n do |server|
      server.vm.hostname = "#{n}.local"
      server.vm.network "private_network", ip: "192.168.59.#{100+i}"
      server.vm.provider "virtualbox" do |vb|
        vb.name = "#{n}.local"
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end

end
