---
version: '3'

tasks:

  default:
    cmds:
      - task --list
      #- task --list-all

  u:
    desc: up
    cmds:
      - docker compose up

  ub:
    desc: up --build
    cmds:
      - docker compose up --build

  d:
    desc: down
    cmds:
      - docker compose down -v --remove-orphans

  e:
    desc: exec
    cmds:
      - docker compose exec ansible bash

  rmi:
    desc: remove images used by services
    cmds:
      - docker compose down -v --remove-orphans --rmi local

  a:
    desc: run ansible-playbook
    cmds:
      - docker compose exec ansible ansible-playbook playbook.yaml
