---
version: '3'

tasks:

  default:
    cmds:
      - task --list

  a:
    desc: run ansible
    dir: ./ansible
    cmds:
      - ansible-playbook playbook.yaml

  at:
    desc: run ansible with --tags option
    dir: ./ansible
    cmds:
      - ansible-playbook --tags {{.TAG}} playbook.yaml
    requires:
      vars: [TAG]
