---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "typesense.fullname" . }}
  labels:
    {{- include "typesense.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  serviceName: {{ include "typesense.fullname" . }}
  selector:
    matchLabels:
      {{- include "typesense.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "typesense.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: typesense
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8108
            - name: peering
              containerPort: 8107
          {{- if .Values.sleep }}
          command: ["sleep"]
          args: ["infinity"]
          {{- else }}
          args:
            - "--config=/config/config.ini"
          {{- end }}
          env:
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "typesense.fullname" . }}
                  key: api-key
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "typesense.fullname" . }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storage.className }}
        storageClassName: {{ .Values.storage.className }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
