---
- name: init setup
  hosts: all
  become: true
  gather_facts: true
  tags: init

  roles:
    - docker

  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: install common tools
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 900  # 15mins
        pkg:
          - libbpf-tools

    - name: pull haporxy docker image
      tags: docker
      become: true
      community.docker.docker_image_pull:
        name: haproxy
        tag: 3.0.8
        pull: not_present

    - name: pull nginx docker image
      tags: docker
      become: true
      community.docker.docker_image_pull:
        name: nginx
        tag: 1.27.4
        pull: not_present

- name: main run
  hosts: all
  become: true
  gather_facts: true
  tags: main

  tasks:
    - include_tasks: "{{ ansible_hostname }}.yaml"
