---
- name: init setup
  hosts: all
  become: true
  gather_facts: true

  roles:
    - docker

  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: install common tools
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 900  # 15mins
        pkg:
          - libbpf-tools

    - name: pull haporxy docker image
      tags: docker
      become: true
      community.docker.docker_image_pull:
        name: haproxy
        tag: 3.0.8
        pull: not_present
