---
- name: init setup
  hosts: all
  become: false
  gather_facts: true

    #vars:
    #  prometheus_targets:

  roles:
    - role: docker
    - role: cadvisor
      tags: cadvisor
    - role: prometheus
      tags: prometheus
    - role: grafana
      tags: grafana
