---

name: xyzzy-play

services:

  xyzzy:
    #image: debian:12.8
    build:
      context: .
    entrypoint:
      - sleep
    command:
      - infinity
    ports:
      - 8080:8080/tcp
    volumes:
      - ${PWD}/src:/src
