Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder "src/", "/src"
  config.vm.network "private_network", ip: "192.168.59.11"
  config.ssh.insert_key = false

  config.vm.provision "shell", path: "provision.sh"
end
