
CPU=2
MEMORY=2048
IP_START=100

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.synced_folder "src/", "/src"
  config.ssh.insert_key = false # use ~/.vagrant.d/insecure_private_key

  nodes = [
    "node10", # master
    "node11", # slave
    "node12", # client
  ]

  nodes.each_with_index do |n,i|
    config.vm.define n do |server|
      server.vm.hostname = "#{n}.local"
      server.vm.network "private_network", ip: "192.168.59.#{IP_START+i}"
      server.vm.provider "virtualbox" do |vb|
        vb.name = "#{n}.local"
        vb.memory = MEMORY
        vb.cpus = CPU
      end
    end
  end

  config.vm.provision "shell", path: "provision.sh"

end
