---
name: nginx

services:
  nginx:
    container_name: nginx
    image: nginx:1.27.4
    restart: unless-stopped
    entrypoint:
      - nginx
    ports:
      - 8081:8081
    volumes:
      - /src/h01/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /src/ssl.pem:/etc/nginx/ssl.pem:ro
      - /src/simple-website:/usr/share/nginx/html:ro
