Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  NodeCount = 3
  (1..NodeCount).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}.local"
      node.vm.network "private_network", ip: "192.168.59.10#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.name = "node#{i}.local"
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end

end
