---
- name: my firsy play
  gather_facts: false
  hosts: all

  tasks:
    - name: test template
      ansible.builtin.template:
        src: templates/test.yaml.j2
        dest: /tmp/test.yaml
      vars:
        test_xxx:
          - a
          - b
