---
- name: my firsy play
  gather_facts: false
  hosts: all

  vars:
    users:
      user1:
        property1: ok
      user2:
        property1: ok2
  roles:
    - roleABC
      #tasks:
      #  - name: test template
      #    ansible.builtin.template:
      #      src: templates/test.yaml.j2
      #      dest: /tmp/{{ item.key }}.yaml
      #    with_dict: "{{ test_xxx }}"
      #    vars:
      #      test_xxx:
      #        a:
      #          path: test
      #        b: ~
