IP="192.168.59.11"


Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  #config.vm.synced_folder "src/", "/src"
  config.ssh.insert_key = false # use ~/.vagrant.d/insecure_private_key

  config.vm.hostname = "debian13-ansible.local"
  config.vm.network "private_network", ip: IP

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ansible_roles_development.local"
    vb.memory = 2048
    vb.cpus = 2
  end

  #config.vm.provision "shell", path: "provision.sh"
end
