Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.synced_folder "src/", "/src"
  config.ssh.insert_key = false # use ~/.vagrant.d/insecure_private_key

  config.vm.hostname = "node00.local"
  config.vm.network "private_network", ip: "192.168.59.10"


  config.vm.provider "virtualbox" do |vb|
    vb.name = "node00.local"
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "provision.sh"
end
